In [29]:
import numpy as np
counts={}
with open('/home/zhongyao/wufang/votenet/scannet/meta_data/scannetv2_train.txt', 'r') as f:
    lines = f.read().splitlines()
for line in lines:
    a = np.load('/home/zhongyao/wufang/votenet/scannet/scannet_train_detection_data40/' + line + '_bbox.npy')
    for i in a:
        if i[-1] not in counts:
            counts[i[-1]] = 1
        else:   
            counts[i[-1]] += 1


In [30]:
counts

{1.0: 6721,
 8.0: 2026,
 7.0: 1271,
 38.0: 1031,
 9.0: 928,
 40.0: 6857,
 39.0: 1985,
 5.0: 4357,
 30.0: 251,
 2.0: 1255,
 15.0: 486,
 29.0: 657,
 36.0: 113,
 34.0: 390,
 3.0: 1427,
 28.0: 116,
 33.0: 201,
 11.0: 661,
 27.0: 481,
 19.0: 279,
 6.0: 406,
 14.0: 551,
 37.0: 253,
 10.0: 300,
 21.0: 386,
 25.0: 177,
 22.0: 614,
 23.0: 1554,
 18.0: 745,
 4.0: 307,
 24.0: 186,
 35.0: 364,
 32.0: 190,
 12.0: 216,
 20.0: 32,
 17.0: 170,
 16.0: 292,
 13.0: 22,
 26.0: 52,
 31.0: 39}

In [4]:
counts = sorted(counts.items(), key=lambda x: x[1], reverse=True)

In [23]:
counts

[(40.0, 6857),
 (1.0, 6721),
 (5.0, 4357),
 (8.0, 2026),
 (39.0, 1985),
 (23.0, 1554),
 (3.0, 1427),
 (7.0, 1271),
 (2.0, 1255),
 (38.0, 1031),
 (9.0, 928),
 (18.0, 745),
 (11.0, 661),
 (29.0, 657),
 (22.0, 614),
 (14.0, 551),
 (15.0, 486),
 (27.0, 481),
 (6.0, 406),
 (34.0, 390),
 (21.0, 386),
 (35.0, 364),
 (4.0, 307),
 (10.0, 300),
 (16.0, 292),
 (19.0, 279),
 (37.0, 253),
 (30.0, 251),
 (12.0, 216),
 (33.0, 201),
 (32.0, 190),
 (24.0, 186),
 (25.0, 177),
 (17.0, 170),
 (28.0, 116),
 (36.0, 113),
 (26.0, 52),
 (31.0, 39),
 (20.0, 32),
 (13.0, 22)]

In [10]:
numbers = [str(int(count[1])) for count in counts]

# 使用逗号将数字连接起来并打印
print(', '.join(numbers))

6857, 6721, 4357, 2026, 1985, 1554, 1427, 1271, 1255, 1031, 928, 745, 661, 657, 614, 551, 486, 481, 406, 390, 386, 364, 307, 300, 292, 279, 253, 251, 216, 201, 190, 186, 177, 170, 116, 113, 52, 39, 32, 22


In [17]:
x=np.load('/home/zhongyao/wufang/votenet/scannet/meta_data/scannet_means.npz')['arr_0']
print(x.shape)

(18, 3)


In [20]:
x=np.load('/home/zhongyao/wufang/votenet/scannet/scannet_train_detection_data40/scene0000_00_bbox.npy')
print(x[0])

[1.48129511 3.52074146 1.85652947 1.74445975 0.23195696 0.57235193
 9.        ]


In [45]:
import numpy as np

size3 = {}
size4 = {}
size5 = {}

with open('/home/zhongyao/wufang/votenet/scannet/meta_data/scannetv2_train.txt', 'r') as f:
    lines = f.read().splitlines()

for line in lines:
    a = np.load('/home/zhongyao/wufang/votenet/scannet/scannet_train_detection_data40/' + line + '_bbox.npy')
    for i in a:
        if i[-1] not in size3:
            size3[i[-1]] = i[3]
            size4[i[-1]] = i[4]
            size5[i[-1]] = i[5]
        else:   
            size3[i[-1]] += i[3]
            size4[i[-1]] += i[4]
            size5[i[-1]] += i[5]
with open('/home/zhongyao/wufang/votenet/scannet/meta_data/scannetv2_val.txt', 'r') as f:
    lines = f.read().splitlines()

# for line in lines:
#     a = np.load('/home/zhongyao/wufang/votenet/scannet/scannet_val_detection_data40/' + line + '_bbox.npy')
#     for i in a:
#         if i[-1] not in size3:
#             size3[i[-1]] = i[3]
#             size4[i[-1]] = i[4]
#             size5[i[-1]] = i[5]
#         else:   
#             size3[i[-1]] += i[3]
#             size4[i[-1]] += i[4]
#             size5[i[-1]] += i[5]
# 计算平均值
average3 = {key: value / counts[key] for key, value in size3.items() if key in counts}
average4 = {key: value / counts[key] for key, value in size4.items() if key in counts}
average5 = {key: value / counts[key] for key, value in size5.items() if key in counts}


In [46]:
average5

{1.0: 1.770031532759628,
 8.0: 1.7190299373918083,
 7.0: 0.6349110067430019,
 38.0: 0.7969744719210813,
 9.0: 1.1885096240981385,
 40.0: 0.3592253533898654,
 39.0: 0.6466654514673374,
 5.0: 0.7050861664251474,
 30.0: 1.077547378274074,
 2.0: 0.2736213394192111,
 15.0: 1.1382653775161187,
 29.0: 0.40359194953238403,
 36.0: 0.5300481055690124,
 34.0: 0.3090853559665191,
 3.0: 0.9764581385950317,
 28.0: 1.6774457867803245,
 33.0: 0.725721286600502,
 11.0: 0.5794232971233607,
 27.0: 0.3776020978436091,
 19.0: 0.7359719618246974,
 6.0: 0.8341014523591314,
 14.0: 0.8650206335551509,
 37.0: 0.35615243391674967,
 10.0: 1.6820667014519373,
 21.0: 0.568248455060424,
 25.0: 0.635974454425149,
 22.0: 0.18658046264213538,
 23.0: 0.29994441452346254,
 18.0: 0.28423646470444314,
 4.0: 1.1926351247858924,
 24.0: 1.3260876007618443,
 35.0: 0.5116600049761953,
 32.0: 0.6640420518423381,
 12.0: 0.2776825423869822,
 20.0: 0.08083783113397658,
 17.0: 0.9582426122006248,
 16.0: 1.6293216076207488,
 13.0: 1.

In [34]:
x=np.load('/home/zhongyao/wufang/votenet/scannet/meta_data/scannet_means.npz')['arr_0']
print(x)

[[0.76966726 0.81160211 0.92573741]
 [1.876858   1.84255952 1.19315654]
 [0.61327999 0.61486087 0.71827014]
 [1.39550063 1.51215451 0.83443565]
 [0.97949596 1.06751485 0.63296875]
 [0.53166301 0.59555772 1.75001483]
 [0.96247056 0.72462326 1.14818682]
 [0.83221924 1.04909355 1.68756634]
 [0.21132214 0.4206159  0.53728459]
 [1.44400728 1.89708334 0.26985747]
 [1.02942616 1.40407966 0.87554322]
 [1.37664116 0.65521793 1.68131292]
 [0.66508189 0.71111926 1.29885307]
 [0.41999174 0.37906947 1.75139715]
 [0.59359559 0.59124924 0.73919014]
 [0.50867595 0.50656087 0.30136236]
 [1.15115265 1.0546296  0.49706794]
 [0.47535286 0.49249493 0.58021168]]


In [47]:
keys_order = [40, 1, 5, 8, 39, 23, 3, 7, 2, 38, 9, 18, 11, 29, 22, 14, 15, 27, 6, 34, 21, 35, 4, 10, 16, 19, 37, 30, 12, 33, 32, 24, 25, 17, 28, 36, 26, 31, 20, 13]

new_arr = np.zeros((len(keys_order), 3))

for i, key in enumerate(keys_order):
    if key in average3 and key in average4 and key in average5:
        new_arr[i] = [average3[key], average4[key], average5[key]]

np.savez('/home/zhongyao/wufang/votenet/scannet/meta_data/mean40.npz', new_arr)

In [49]:
x=np.load('/home/zhongyao/wufang/votenet/scannet/meta_data/mean40.npz')['arr_0']
print(x.shape)

(40, 3)
